import admin from 'firebase-admin';
import fs from 'fs';

// Read the service account key file synchronously
const serviceAccount = JSON.parse(fs.readFileSync('./serviceAccountKey.json', 'utf8'));

// Initialize Firebase Admin SDK
admin.initializeApp({
    credential: admin.credential.cert(serviceAccount),
});

const db = admin.firestore();

// Array of motherboard data
const mb_id = [
    {
      mb_id: '1',
      TDP: 95,
      bios_version: '1.0.0',
      bluetooth: true,
      brand: 'ASUS',
      chipset: 'Z690',
      form_factor: 'ATX',
      m2_slots: true,
      max_memory: 128,
      memory_speed: 4800,
      memory_type: 'DDR5',
      model: 'ROG Strix Z690-E',
      price: 399,
      ram_slots: 4,
      socket: 'LGA 1700'
    },
    {
      mb_id: '2',
      TDP: 125,
      bios_version: '2.0.1',
      bluetooth: true,
      brand: 'MSI',
      chipset: 'B550',
      form_factor: 'ATX',
      m2_slots: true,
      max_memory: 128,
      memory_speed: 4400,
      memory_type: 'DDR4',
      model: 'MAG B550 TOMAHAWK',
      price: 179,
      ram_slots: 4,
      socket: 'AM4'
    },
    {
      mb_id: '3',
      TDP: 105,
      bios_version: '1.2.3',
      bluetooth: false,
      brand: 'Gigabyte',
      chipset: 'Z590',
      form_factor: 'Micro-ATX',
      m2_slots: true,
      max_memory: 64,
      memory_speed: 3200,
      memory_type: 'DDR4',
      model: 'AORUS Z590 Elite AX',
      price: 229,
      ram_slots: 4,
      socket: 'LGA 1200'
    },
    {
      mb_id: '4',
      TDP: 95,
      bios_version: '3.0.0',
      bluetooth: true,
      brand: 'ASRock',
      chipset: 'X570',
      form_factor: 'Mini-ITX',
      m2_slots: true,
      max_memory: 64,
      memory_speed: 3600,
      memory_type: 'DDR4',
      model: 'ASRock X570 Phantom Gaming-ITX',
      price: 269,
      ram_slots: 2,
      socket: 'AM4'
    },
    {
      mb_id: '5',
      TDP: 105,
      bios_version: '1.4.0',
      bluetooth: false,
      brand: 'EVGA',
      chipset: 'Z590',
      form_factor: 'ATX',
      m2_slots: true,
      max_memory: 128,
      memory_speed: 4000,
      memory_type: 'DDR4',
      model: 'EVGA Z590 FTW WIFI',
      price: 349,
      ram_slots: 4,
      socket: 'LGA 1200'
    },
    {
      mb_id: '6',
      TDP: 125,
      bios_version: '2.2.0',
      bluetooth: true,
      brand: 'MSI',
      chipset: 'X570',
      form_factor: 'ATX',
      m2_slots: true,
      max_memory: 128,
      memory_speed: 4600,
      memory_type: 'DDR4',
      model: 'MSI MEG X570 UNIFY',
      price: 299,
      ram_slots: 4,
      socket: 'AM4'
    },
    {
      mb_id: '7',
      TDP: 65,
      bios_version: '1.1.1',
      bluetooth: false,
      brand: 'Gigabyte',
      chipset: 'B450',
      form_factor: 'Micro-ATX',
      m2_slots: true,
      max_memory: 64,
      memory_speed: 3600,
      memory_type: 'DDR4',
      model: 'Gigabyte B450M DS3H',
      price: 99,
      ram_slots: 4,
      socket: 'AM4'
    },
    {
      mb_id: '8',
      TDP: 125,
      bios_version: '2.1.0',
      bluetooth: true,
      brand: 'ASUS',
      chipset: 'X570',
      form_factor: 'ATX',
      m2_slots: true,
      max_memory: 128,
      memory_speed: 5100,
      memory_type: 'DDR4',
      model: 'ASUS ROG Crosshair VIII Hero',
      price: 379,
      ram_slots: 4,
      socket: 'AM4'
    },
    {
      mb_id: '9',
      TDP: 85,
      bios_version: '1.3.3',
      bluetooth: false,
      brand: 'ASRock',
      chipset: 'B450',
      form_factor: 'ATX',
      m2_slots: true,
      max_memory: 64,
      memory_speed: 3000,
      memory_type: 'DDR4',
      model: 'ASRock B450 Steel Legend',
      price: 119,
      ram_slots: 4,
      socket: 'AM4'
    },
    {
      mb_id: '10',
      TDP: 105,
      bios_version: '2.4.0',
      bluetooth: true,
      brand: 'MSI',
      chipset: 'Z490',
      form_factor: 'ATX',
      m2_slots: true,
      max_memory: 128,
      memory_speed: 4800,
      memory_type: 'DDR4',
      model: 'MSI MPG Z490 GAMING EDGE WIFI',
      price: 209,
      ram_slots: 4,
      socket: 'LGA 1200'
    },
    {
      mb_id: '11',
      TDP: 85,
      bios_version: '1.1.0',
      bluetooth: true,
      brand: 'Gigabyte',
      chipset: 'X299',
      form_factor: 'E-ATX',
      m2_slots: true,
      max_memory: 128,
      memory_speed: 2933,
      memory_type: 'DDR4',
      model: 'Gigabyte X299X AORUS Master',
      price: 449,
      ram_slots: 8,
      socket: 'LGA 2066'
    },
    {
      mb_id: '12',
      TDP: 125,
      bios_version: '1.5.0',
      bluetooth: true,
      brand: 'ASUS',
      chipset: 'B550',
      form_factor: 'ATX',
      m2_slots: true,
      max_memory: 128,
      memory_speed: 4600,
      memory_type: 'DDR4',
      model: 'ASUS TUF Gaming B550-PLUS',
      price: 189,
      ram_slots: 4,
      socket: 'AM4'
    },
    {
      mb_id: '13',
      TDP: 105,
      bios_version: '1.3.0',
      bluetooth: true,
      brand: 'MSI',
      chipset: 'X470',
      form_factor: 'ATX',
      m2_slots: true,
      max_memory: 128,
      memory_speed: 4133,
      memory_type: 'DDR4',
      model: 'MSI X470 GAMING PRO CARBON',
      price: 169,
      ram_slots: 4,
      socket: 'AM4'
    },
    {
      mb_id: '14',
      TDP: 95,
      bios_version: '1.2.1',
      bluetooth: false,
      brand: 'ASRock',
      chipset: 'B550',
      form_factor: 'Micro-ATX',
      m2_slots: true,
      max_memory: 64,
      memory_speed: 4000,
      memory_type: 'DDR4',
      model: 'ASRock B550M Pro4',
      price: 109,
      ram_slots: 4,
      socket: 'AM4'
    },
    {
      mb_id: '15',
      TDP: 125,
      bios_version: '2.0.0',
      bluetooth: true,
      brand: 'Gigabyte',
      chipset: 'Z590',
      form_factor: 'ATX',
      m2_slots: true,
      max_memory: 128,
      memory_speed: 5000,
      memory_type: 'DDR4',
      model: 'Gigabyte Z590 AORUS ULTRA',
      price: 329,
      ram_slots: 4,
      socket: 'LGA 1200'
    },
    {
      mb_id: '16',
      TDP: 105,
      bios_version: '1.1.5',
      bluetooth: false,
      brand: 'ASUS',
      chipset: 'B450',
      form_factor: 'Micro-ATX',
      m2_slots: true,
      max_memory: 64,
      memory_speed: 3200,
      memory_type: 'DDR4',
      model: 'ASUS Prime B450M-A',
      price: 99,
      ram_slots: 4,
      socket: 'AM4'
    },
    {
      mb_id: '17',
      TDP: 95,
      bios_version: '1.1.1',
      bluetooth: true,
      brand: 'MSI',
      chipset: 'Z390',
      form_factor: 'ATX',
      m2_slots: true,
      max_memory: 128,
      memory_speed: 4400,
      memory_type: 'DDR4',
      model: 'MSI MPG Z390 Gaming Pro Carbon',
      price: 239,
      ram_slots: 4,
      socket: 'LGA 1151'
    },
    {
      mb_id: '18',
      TDP: 85,
      bios_version: '1.3.3',
      bluetooth: false,
      brand: 'ASRock',
      chipset: 'X470',
      form_factor: 'Micro-ATX',
      m2_slots: true,
      max_memory: 64,
      memory_speed: 3600,
      memory_type: 'DDR4',
      model: 'ASRock X470 Gaming K4',
      price: 159,
      ram_slots: 4,
      socket: 'AM4'
    },
    {
      mb_id: '19',
      TDP: 125,
      bios_version: '2.1.0',
      bluetooth: true,
      brand: 'ASUS',
      chipset: 'Z490',
      form_factor: 'ATX',
      m2_slots: true,
      max_memory: 128,
      memory_speed: 4800,
      memory_type: 'DDR4',
      model: 'ASUS Z490 ROG Maximus XII Hero',
      price: 409,
      ram_slots: 4,
      socket: 'LGA 1200'
    },
    {
      mb_id: '20',
      TDP: 95,
      bios_version: '1.0.0',
      bluetooth: false,
      brand: 'Gigabyte',
      chipset: 'B360',
      form_factor: 'Micro-ATX',
      m2_slots: true,
      max_memory: 64,
      memory_speed: 2666,
      memory_type: 'DDR4',
      model: 'Gigabyte B360M DS3H',
      price: 79,
      ram_slots: 4,
      socket: 'LGA 1151'
    },
    {
      mb_id: '21',
      TDP: 105,
      bios_version: '1.4.0',
      bluetooth: true,
      brand: 'MSI',
      chipset: 'Z370',
      form_factor: 'ATX',
      m2_slots: true,
      max_memory: 128,
      memory_speed: 4000,
      memory_type: 'DDR4',
      model: 'MSI Z370 GAMING PRO CARBON',
      price: 219,
      ram_slots: 4,
      socket: 'LGA 1151'
    },
    {
      mb_id: '22',
      TDP: 85,
      bios_version: '1.3.1',
      bluetooth: true,
      brand: 'ASRock',
      chipset: 'Z370',
      form_factor: 'ATX',
      m2_slots: true,
      max_memory: 64,
      memory_speed: 3200,
      memory_type: 'DDR4',
      model: 'ASRock Z370 Extreme4',
      price: 149,
      ram_slots: 4,
      socket: 'LGA 1151'
    },
    {
      mb_id: '23',
      TDP: 95,
      bios_version: '2.0.1',
      bluetooth: true,
      brand: 'ASUS',
      chipset: 'B460',
      form_factor: 'Micro-ATX',
      m2_slots: true,
      max_memory: 64,
      memory_speed: 2933,
      memory_type: 'DDR4',
      model: 'ASUS Prime B460M-A',
      price: 109,
      ram_slots: 4,
      socket: 'LGA 1200'
    },
    {
      mb_id: '24',
      TDP: 125,
      bios_version: '1.2.2',
      bluetooth: true,
      brand: 'Gigabyte',
      chipset: 'X570',
      form_factor: 'ATX',
      m2_slots: true,
      max_memory: 128,
      memory_speed: 5000,
      memory_type: 'DDR4',
      model: 'Gigabyte X570 AORUS Elite',
      price: 299,
      ram_slots: 4,
      socket: 'AM4'
    },
    {
      mb_id: '25',
      TDP: 95,
      bios_version: '1.1.1',
      bluetooth: false,
      brand: 'MSI',
      chipset: 'H310',
      form_factor: 'Micro-ATX',
      m2_slots: false,
      max_memory: 32,
      memory_speed: 2400,
      memory_type: 'DDR4',
      model: 'MSI H310M PRO-VDH Plus',
      price: 69,
      ram_slots: 2,
      socket: 'LGA 1151'
    },
    {
      mb_id: '26',
      TDP: 125,
      bios_version: '1.3.0',
      bluetooth: true,
      brand: 'ASUS',
      chipset: 'B450',
      form_factor: 'ATX',
      m2_slots: true,
      max_memory: 128,
      memory_speed: 3466,
      memory_type: 'DDR4',
      model: 'ASUS ROG Strix B450-F',
      price: 139,
      ram_slots: 4,
      socket: 'AM4'
    },
    {
      mb_id: '27',
      TDP: 85,
      bios_version: '1.1.4',
      bluetooth: false,
      brand: 'Gigabyte',
      chipset: 'A320',
      form_factor: 'Micro-ATX',
      m2_slots: true,
      max_memory: 64,
      memory_speed: 3200,
      memory_type: 'DDR4',
      model: 'Gigabyte GA-A320M-S2H',
      price: 69,
      ram_slots: 2,
      socket: 'AM4'
    },
    {
      mb_id: '28',
      TDP: 95,
      bios_version: '2.1.0',
      bluetooth: true,
      brand: 'ASRock',
      chipset: 'Z590',
      form_factor: 'ATX',
      m2_slots: true,
      max_memory: 128,
      memory_speed: 5000,
      memory_type: 'DDR4',
      model: 'ASRock Z590 Steel Legend',
      price: 219,
      ram_slots: 4,
      socket: 'LGA 1200'
    },
    {
      mb_id: '29',
      TDP: 125,
      bios_version: '3.0.0',
      bluetooth: true,
      brand: 'MSI',
      chipset: 'B550',
      form_factor: 'ATX',
      m2_slots: true,
      max_memory: 128,
      memory_speed: 4733,
      memory_type: 'DDR4',
      model: 'MSI MPG B550 GAMING EDGE WIFI',
      price: 189,
      ram_slots: 4,
      socket: 'AM4'
    },
    {
      mb_id: '30',
      TDP: 105,
      bios_version: '2.2.0',
      bluetooth: false,
      brand: 'Gigabyte',
      chipset: 'Z390',
      form_factor: 'Mini-ITX',
      m2_slots: true,
      max_memory: 64,
      memory_speed: 4600,
      memory_type: 'DDR4',
      model: 'Gigabyte Z390 I AORUS PRO WIFI',
      price: 209,
      ram_slots: 2,
      socket: 'LGA 1151'
    },
    {
      mb_id: '31',
      TDP: 95,
      bios_version: '1.5.0',
      bluetooth: true,
      brand: 'ASUS',
      chipset: 'X470',
      form_factor: 'Micro-ATX',
      m2_slots: true,
      max_memory: 64,
      memory_speed: 3600,
      memory_type: 'DDR4',
      model: 'ASUS TUF X470-PLUS GAMING',
      price: 159,
      ram_slots: 4,
      socket: 'AM4'
    },
    {
      mb_id: '32',
      TDP: 125,
      bios_version: '1.3.1',
      bluetooth: true,
      brand: 'ASRock',
      chipset: 'B550',
      form_factor: 'ATX',
      m2_slots: true,
      max_memory: 128,
      memory_speed: 5000,
      memory_type: 'DDR4',
      model: 'ASRock B550 Phantom Gaming 4',
      price: 179,
      ram_slots: 4,
      socket: 'AM4'
    },
    {
      mb_id: '33',
      TDP: 105,
      bios_version: '2.1.5',
      bluetooth: false,
      brand: 'MSI',
      chipset: 'Z370',
      form_factor: 'Micro-ATX',
      m2_slots: true,
      max_memory: 64,
      memory_speed: 4000,
      memory_type: 'DDR4',
      model: 'MSI Z370M Mortar',
      price: 139,
      ram_slots: 4,
      socket: 'LGA 1151'
    },
    {
      mb_id: '34',
      TDP: 95,
      bios_version: '1.4.0',
      bluetooth: true,
      brand: 'Gigabyte',
      chipset: 'H470',
      form_factor: 'Micro-ATX',
      m2_slots: true,
      max_memory: 64,
      memory_speed: 2933,
      memory_type: 'DDR4',
      model: 'Gigabyte H470M DS3H',
      price: 99,
      ram_slots: 4,
      socket: 'LGA 1200'
    },
    {
      mb_id: '35',
      TDP: 125,
      bios_version: '1.0.0',
      bluetooth: true,
      brand: 'ASUS',
      chipset: 'Z690',
      form_factor: 'E-ATX',
      m2_slots: true,
      max_memory: 128,
      memory_speed: 6000,
      memory_type: 'DDR5',
      model: 'ASUS ROG Maximus Z690 Extreme',
      price: 999,
      ram_slots: 4,
      socket: 'LGA 1700'
    },
    {
      mb_id: '36',
      TDP: 85,
      bios_version: '1.2.0',
      bluetooth: false,
      brand: 'ASRock',
      chipset: 'B360',
      form_factor: 'ATX',
      m2_slots: true,
      max_memory: 64,
      memory_speed: 2666,
      memory_type: 'DDR4',
      model: 'ASRock B360 Pro4',
      price: 89,
      ram_slots: 4,
      socket: 'LGA 1151'
    },
    {
      mb_id: '37',
      TDP: 105,
      bios_version: '1.1.5',
      bluetooth: true,
      brand: 'MSI',
      chipset: 'X470',
      form_factor: 'ATX',
      m2_slots: true,
      max_memory: 128,
      memory_speed: 4133,
      memory_type: 'DDR4',
      model: 'MSI X470 Gaming Plus',
      price: 149,
      ram_slots: 4,
      socket: 'AM4'
    },
    {
      mb_id: '38',
      TDP: 125,
      bios_version: '2.2.1',
      bluetooth: true,
      brand: 'Gigabyte',
      chipset: 'Z690',
      form_factor: 'ATX',
      m2_slots: true,
      max_memory: 128,
      memory_speed: 6000,
      memory_type: 'DDR5',
      model: 'Gigabyte Z690 AORUS Master',
      price: 469,
      ram_slots: 4,
      socket: 'LGA 1700'
    },
    {
      mb_id: '39',
      TDP: 85,
      bios_version: '1.3.0',
      bluetooth: false,
      brand: 'ASUS',
      chipset: 'H410',
      form_factor: 'Micro-ATX',
      m2_slots: true,
      max_memory: 64,
      memory_speed: 2933,
      memory_type: 'DDR4',
      model: 'ASUS Prime H410M-E',
      price: 69,
      ram_slots: 2,
      socket: 'LGA 1200'
    },
    {
      mb_id: '40',
      TDP: 125,
      bios_version: '1.5.0',
      bluetooth: true,
      brand: 'MSI',
      chipset: 'Z690',
      form_factor: 'ATX',
      m2_slots: true,
      max_memory: 128,
      memory_speed: 5333,
      memory_type: 'DDR5',
      model: 'MSI MPG Z690 Carbon WIFI',
      price: 399,
      ram_slots: 4,
      socket: 'LGA 1700'
    },
    {
      mb_id: '41',
      TDP: 105,
      bios_version: '1.1.0',
      bluetooth: true,
      brand: 'ASRock',
      chipset: 'B450',
      form_factor: 'ATX',
      m2_slots: true,
      max_memory: 64,
      memory_speed: 3466,
      memory_type: 'DDR4',
      model: 'ASRock B450M-HDV',
      price: 89,
      ram_slots: 2,
      socket: 'AM4'
    },
    {
      mb_id: '42',
      TDP: 95,
      bios_version: '2.0.0',
      bluetooth: false,
      brand: 'Gigabyte',
      chipset: 'B460',
      form_factor: 'ATX',
      m2_slots: true,
      max_memory: 64,
      memory_speed: 2933,
      memory_type: 'DDR4',
      model: 'Gigabyte B460M DS3H',
      price: 99,
      ram_slots: 4,
      socket: 'LGA 1200'
    },
    {
      mb_id: '43',
      TDP: 125,
      bios_version: '1.1.3',
      bluetooth: true,
      brand: 'MSI',
      chipset: 'Z590',
      form_factor: 'ATX',
      m2_slots: true,
      max_memory: 128,
      memory_speed: 5333,
      memory_type: 'DDR4',
      model: 'MSI Z590 PRO WIFI',
      price: 229,
      ram_slots: 4,
      socket: 'LGA 1200'
    },
    {
      mb_id: '44',
      TDP: 85,
      bios_version: '1.0.1',
      bluetooth: false,
      brand: 'ASUS',
      chipset: 'A320',
      form_factor: 'Micro-ATX',
      m2_slots: true,
      max_memory: 64,
      memory_speed: 3200,
      memory_type: 'DDR4',
      model: 'ASUS Prime A320M-K',
      price: 59,
      ram_slots: 2,
      socket: 'AM4'
    },
    {
      mb_id: '45',
      TDP: 125,
      bios_version: '1.3.0',
      bluetooth: true,
      brand: 'Gigabyte',
      chipset: 'X570',
      form_factor: 'ATX',
      m2_slots: true,
      max_memory: 128,
      memory_speed: 5000,
      memory_type: 'DDR4',
      model: 'Gigabyte X570 AORUS Master',
      price: 399,
      ram_slots: 4,
      socket: 'AM4'
    },
    {
      mb_id: '46',
      TDP: 105,
      bios_version: '1.1.2',
      bluetooth: false,
      brand: 'MSI',
      chipset: 'B550',
      form_factor: 'Micro-ATX',
      m2_slots: true,
      max_memory: 64,
      memory_speed: 4400,
      memory_type: 'DDR4',
      model: 'MSI B550M PRO-VDH WIFI',
      price: 129,
      ram_slots: 2,
      socket: 'AM4'
    },
    {
      mb_id: '47',
      TDP: 95,
      bios_version: '2.1.0',
      bluetooth: true,
      brand: 'ASRock',
      chipset: 'Z490',
      form_factor: 'ATX',
      m2_slots: true,
      max_memory: 128,
      memory_speed: 4800,
      memory_type: 'DDR4',
      model: 'ASRock Z490 Phantom Gaming 4',
      price: 169,
      ram_slots: 4,
      socket: 'LGA 1200'
    },
    {
      mb_id: '48',
      TDP: 85,
      bios_version: '1.1.0',
      bluetooth: false,
      brand: 'ASUS',
      chipset: 'B450',
      form_factor: 'Micro-ATX',
      m2_slots: true,
      max_memory: 64,
      memory_speed: 3200,
      memory_type: 'DDR4',
      model: 'ASUS TUF B450M-PLUS Gaming',
      price: 109,
      ram_slots: 4,
      socket: 'AM4'
    },
    {
      mb_id: '49',
      TDP: 105,
      bios_version: '1.2.0',
      bluetooth: true,
      brand: 'Gigabyte',
      chipset: 'Z590',
      form_factor: 'ATX',
      m2_slots: true,
      max_memory: 128,
      memory_speed: 5333,
      memory_type: 'DDR4',
      model: 'Gigabyte Z590 AORUS PRO AX',
      price: 299,
      ram_slots: 4,
      socket: 'LGA 1200'
    },
    {
      mb_id: '50',
      TDP: 125,
      bios_version: '1.3.5',
      bluetooth: true,
      brand: 'MSI',
      chipset: 'X570',
      form_factor: 'ATX',
      m2_slots: true,
      max_memory: 128,
      memory_speed: 5000,
      memory_type: 'DDR4',
      model: 'MSI MEG X570 Unify',
      price: 299,
      ram_slots: 4,
      socket: 'AM4'
    }
    // Add the rest of the 50 motherboards in the same structure...
  ];
  

// Function to insert all motherboards
async function addMotherboards() {
  const batch = db.batch();

  mb_id.forEach((MB) => {
    const docRef = db.collection('Motherboard').doc(MB.mb_id.toString());
    batch.set(docRef, MB);
  });

  await batch.commit();
  console.log('Motherboards added successfully!');
}

addMotherboards().catch(console.error);