import admin from 'firebase-admin';
import fs from 'fs';

// Read the service account key file synchronously
const serviceAccount = JSON.parse(fs.readFileSync('./serviceAccountKey.json', 'utf8'));

// Initialize Firebase Admin SDK
admin.initializeApp({
    credential: admin.credential.cert(serviceAccount),
});

// Get Firestore
const db = admin.firestore();

  const ram_id = [
    {
      ram_id: '1',
      brand: 'Corsair',
      capacity: 16,
      form_factor: 'DIMM',
      heat_spreader: true,
      latency: 16,
      memory_type: 'DDR4',
      model: 'Vengeance LPX',
      modules: '2x8GB',
      price: 89,
      speed: 3200,
      voltage: 1.35
    },
    {
      ram_id: '2',
      brand: 'G.Skill',
      capacity: 32,
      form_factor: 'DIMM',
      heat_spreader: true,
      latency: 16,
      memory_type: 'DDR4',
      model: 'Ripjaws V',
      modules: '2x16GB',
      price: 149,
      speed: 3200,
      voltage: 1.35
    },
    {
      ram_id: '3',
      brand: 'Kingston',
      capacity: 16,
      form_factor: 'DIMM',
      heat_spreader: true,
      latency: 15,
      memory_type: 'DDR4',
      model: 'Fury Beast',
      modules: '2x8GB',
      price: 89,
      speed: 3200,
      voltage: 1.35
    },
    {
      ram_id: '4',
      brand: 'Crucial',
      capacity: 8,
      form_factor: 'SO-DIMM',
      heat_spreader: false,
      latency: 17,
      memory_type: 'DDR4',
      model: 'Ballistix',
      modules: '1x8GB',
      price: 45,
      speed: 2666,
      voltage: 1.2
    },
    {
      ram_id: '5',
      brand: 'Patriot',
      capacity: 16,
      form_factor: 'DIMM',
      heat_spreader: true,
      latency: 19,
      memory_type: 'DDR4',
      model: 'Viper 4',
      modules: '2x8GB',
      price: 79,
      speed: 3200,
      voltage: 1.35
    },
    {
      ram_id: '6',
      brand: 'Teamgroup',
      capacity: 32,
      form_factor: 'DIMM',
      heat_spreader: true,
      latency: 16,
      memory_type: 'DDR4',
      model: 'T-Force Delta RGB',
      modules: '2x16GB',
      price: 169,
      speed: 3200,
      voltage: 1.35
    },
    {
      ram_id: '7',
      brand: 'HyperX',
      capacity: 16,
      form_factor: 'DIMM',
      heat_spreader: true,
      latency: 15,
      memory_type: 'DDR4',
      model: 'Predator',
      modules: '2x8GB',
      price: 99,
      speed: 3200,
      voltage: 1.35
    },
    {
      ram_id: '8',
      brand: 'Ballistix',
      capacity: 16,
      form_factor: 'SO-DIMM',
      heat_spreader: true,
      latency: 16,
      memory_type: 'DDR4',
      model: 'Sport LT',
      modules: '1x16GB',
      price: 75,
      speed: 3200,
      voltage: 1.35
    },
    {
      ram_id: '9',
      brand: 'ADATA',
      capacity: 8,
      form_factor: 'DIMM',
      heat_spreader: false,
      latency: 19,
      memory_type: 'DDR4',
      model: 'XPG GAMMIX D30',
      modules: '1x8GB',
      price: 40,
      speed: 2666,
      voltage: 1.2
    },
    {
      ram_id: '10',
      brand: 'GeIL',
      capacity: 32,
      form_factor: 'DIMM',
      heat_spreader: true,
      latency: 16,
      memory_type: 'DDR4',
      model: 'Super Luce',
      modules: '2x16GB',
      price: 159,
      speed: 3200,
      voltage: 1.35
    },
    {
      ram_id: '11',
      brand: 'Corsair',
      capacity: 32,
      form_factor: 'DIMM',
      heat_spreader: true,
      latency: 18,
      memory_type: 'DDR4',
      model: 'Vengeance LPX',
      modules: '4x8GB',
      price: 179,
      speed: 3200,
      voltage: 1.35
    },
    {
      ram_id: '12',
      brand: 'G.Skill',
      capacity: 16,
      form_factor: 'DIMM',
      heat_spreader: true,
      latency: 14,
      memory_type: 'DDR4',
      model: 'Trident Z',
      modules: '2x8GB',
      price: 129,
      speed: 3600,
      voltage: 1.35
    },
    {
      ram_id: '13',
      brand: 'Kingston',
      capacity: 8,
      form_factor: 'SO-DIMM',
      heat_spreader: false,
      latency: 19,
      memory_type: 'DDR4',
      model: 'Fury Impact',
      modules: '1x8GB',
      price: 40,
      speed: 2400,
      voltage: 1.2
    },
    {
      ram_id: '14',
      brand: 'Crucial',
      capacity: 16,
      form_factor: 'DIMM',
      heat_spreader: true,
      latency: 16,
      memory_type: 'DDR4',
      model: 'Ballistix MAX',
      modules: '2x8GB',
      price: 109,
      speed: 3600,
      voltage: 1.35
    },
    {
      ram_id: '15',
      brand: 'Patriot',
      capacity: 8,
      form_factor: 'DIMM',
      heat_spreader: true,
      latency: 18,
      memory_type: 'DDR4',
      model: 'Viper Steel',
      modules: '1x8GB',
      price: 44,
      speed: 3200,
      voltage: 1.35
    },
    {
      ram_id: '16',
      brand: 'Teamgroup',
      capacity: 16,
      form_factor: 'DIMM',
      heat_spreader: true,
      latency: 16,
      memory_type: 'DDR4',
      model: 'T-Force Dark Z',
      modules: '2x8GB',
      price: 79,
      speed: 3200,
      voltage: 1.35
    },
    {
      ram_id: '17',
      brand: 'HyperX',
      capacity: 32,
      form_factor: 'DIMM',
      heat_spreader: true,
      latency: 16,
      memory_type: 'DDR4',
      model: 'Fury RGB',
      modules: '2x16GB',
      price: 169,
      speed: 3200,
      voltage: 1.35
    },
    {
      ram_id: '18',
      brand: 'Ballistix',
      capacity: 16,
      form_factor: 'SO-DIMM',
      heat_spreader: true,
      latency: 18,
      memory_type: 'DDR4',
      model: 'Sport LT',
      modules: '1x16GB',
      price: 79,
      speed: 3200,
      voltage: 1.35
    },
    {
      ram_id: '19',
      brand: 'ADATA',
      capacity: 32,
      form_factor: 'DIMM',
      heat_spreader: true,
      latency: 20,
      memory_type: 'DDR4',
      model: 'XPG GAMMIX D30',
      modules: '2x16GB',
      price: 159,
      speed: 3200,
      voltage: 1.35
    },
    {
      ram_id: '20',
      brand: 'GeIL',
      capacity: 8,
      form_factor: 'DIMM',
      heat_spreader: true,
      latency: 18,
      memory_type: 'DDR4',
      model: 'Super Luce',
      modules: '1x8GB',
      price: 42,
      speed: 2666,
      voltage: 1.2
    },
    {
      ram_id: '21',
      brand: 'Corsair',
      capacity: 16,
      form_factor: 'DIMM',
      heat_spreader: true,
      latency: 16,
      memory_type: 'DDR4',
      model: 'Vengeance RGB',
      modules: '2x8GB',
      price: 99,
      speed: 3200,
      voltage: 1.35
    },
    {
      ram_id: '22',
      brand: 'G.Skill',
      capacity: 32,
      form_factor: 'DIMM',
      heat_spreader: true,
      latency: 15,
      memory_type: 'DDR4',
      model: 'Trident Z Royal',
      modules: '2x16GB',
      price: 229,
      speed: 3600,
      voltage: 1.35
    },
    {
      ram_id: '23',
      brand: 'Kingston',
      capacity: 16,
      form_factor: 'DIMM',
      heat_spreader: true,
      latency: 15,
      memory_type: 'DDR4',
      model: 'HyperX Predator',
      modules: '2x8GB',
      price: 109,
      speed: 3200,
      voltage: 1.35
    },
    {
      ram_id: '24',
      brand: 'Crucial',
      capacity: 8,
      form_factor: 'SO-DIMM',
      heat_spreader: false,
      latency: 22,
      memory_type: 'DDR4',
      model: 'CT8G4SFD824A',
      modules: '1x8GB',
      price: 37,
      speed: 2400,
      voltage: 1.2
    },
    {
      ram_id: '25',
      brand: 'Patriot',
      capacity: 16,
      form_factor: 'DIMM',
      heat_spreader: true,
      latency: 18,
      memory_type: 'DDR4',
      model: 'Viper Gaming',
      modules: '2x8GB',
      price: 79,
      speed: 3200,
      voltage: 1.35
    },
    {
      ram_id: '26',
      brand: 'Teamgroup',
      capacity: 32,
      form_factor: 'DIMM',
      heat_spreader: true,
      latency: 18,
      memory_type: 'DDR4',
      model: 'T-Force Vulcan',
      modules: '2x16GB',
      price: 149,
      speed: 3200,
      voltage: 1.35
    },
    {
      ram_id: '27',
      brand: 'HyperX',
      capacity: 16,
      form_factor: 'DIMM',
      heat_spreader: true,
      latency: 15,
      memory_type: 'DDR4',
      model: 'Fury Ultra',
      modules: '2x8GB',
      price: 99,
      speed: 3200,
      voltage: 1.35
    },
    {
      ram_id: '28',
      brand: 'Ballistix',
      capacity: 32,
      form_factor: 'DIMM',
      heat_spreader: true,
      latency: 16,
      memory_type: 'DDR4',
      model: 'Sport LT',
      modules: '4x8GB',
      price: 169,
      speed: 3200,
      voltage: 1.35
    },
    {
      ram_id: '29',
      brand: 'ADATA',
      capacity: 16,
      form_factor: 'DIMM',
      heat_spreader: true,
      latency: 18,
      memory_type: 'DDR4',
      model: 'XPG GAMMIX D20',
      modules: '2x8GB',
      price: 89,
      speed: 3200,
      voltage: 1.35
    },
    {
      ram_id: '30',
      brand: 'GeIL',
      capacity: 16,
      form_factor: 'SO-DIMM',
      heat_spreader: true,
      latency: 16,
      memory_type: 'DDR4',
      model: 'Super Luce RGB',
      modules: '1x16GB',
      price: 79,
      speed: 3200,
      voltage: 1.35
    },
    {
      ram_id: '31',
      brand: 'Corsair',
      capacity: 8,
      form_factor: 'DIMM',
      heat_spreader: true,
      latency: 16,
      memory_type: 'DDR4',
      model: 'Vengeance LPX',
      modules: '1x8GB',
      price: 44,
      speed: 2666,
      voltage: 1.2
    },
    {
      ram_id: '32',
      brand: 'G.Skill',
      capacity: 32,
      form_factor: 'DIMM',
      heat_spreader: true,
      latency: 14,
      memory_type: 'DDR4',
      model: 'Trident Z Neo',
      modules: '2x16GB',
      price: 199,
      speed: 3600,
      voltage: 1.35
    },
    {
      ram_id: '33',
      brand: 'Kingston',
      capacity: 8,
      form_factor: 'SO-DIMM',
      heat_spreader: false,
      latency: 20,
      memory_type: 'DDR4',
      model: 'KVR24S17S8/8',
      modules: '1x8GB',
      price: 36,
      speed: 2400,
      voltage: 1.2
    },
    {
      ram_id: '34',
      brand: 'Crucial',
      capacity: 16,
      form_factor: 'DIMM',
      heat_spreader: false,
      latency: 18,
      memory_type: 'DDR4',
      model: 'CT16G4DFD8266',
      modules: '1x16GB',
      price: 89,
      speed: 2666,
      voltage: 1.2
    },
    {
      ram_id: '35',
      brand: 'Patriot',
      capacity: 8,
      form_factor: 'DIMM',
      heat_spreader: false,
      latency: 22,
      memory_type: 'DDR4',
      model: 'Signature Line',
      modules: '1x8GB',
      price: 35,
      speed: 2400,
      voltage: 1.2
    },
    {
      ram_id: '36',
      brand: 'Teamgroup',
      capacity: 16,
      form_factor: 'DIMM',
      heat_spreader: true,
      latency: 16,
      memory_type: 'DDR4',
      model: 'T-Force Delta',
      modules: '2x8GB',
      price: 79,
      speed: 3200,
      voltage: 1.35
    },
    {
      ram_id: '37',
      brand: 'HyperX',
      capacity: 32,
      form_factor: 'DIMM',
      heat_spreader: true,
      latency: 16,
      memory_type: 'DDR4',
      model: 'Fury S',
      modules: '2x16GB',
      price: 159,
      speed: 3200,
      voltage: 1.35
    },
    {
      ram_id: '38',
      brand: 'Ballistix',
      capacity: 16,
      form_factor: 'SO-DIMM',
      heat_spreader: true,
      latency: 18,
      memory_type: 'DDR4',
      model: 'Sport LT',
      modules: '1x16GB',
      price: 79,
      speed: 3200,
      voltage: 1.35
    },
    {
      ram_id: '39',
      brand: 'ADATA',
      capacity: 32,
      form_factor: 'DIMM',
      heat_spreader: true,
      latency: 20,
      memory_type: 'DDR4',
      model: 'XPG D60G',
      modules: '2x16GB',
      price: 179,
      speed: 3600,
      voltage: 1.35
    },
    {
      ram_id: '40',
      brand: 'GeIL',
      capacity: 16,
      form_factor: 'DIMM',
      heat_spreader: true,
      latency: 16,
      memory_type: 'DDR4',
      model: 'Super Luce RGB',
      modules: '2x8GB',
      price: 89,
      speed: 3200,
      voltage: 1.35
    }
  ];



  async function addRAMs() {
    const batch = db.batch();
  
    ram_id.forEach((RAM) => {
      const docRef = db.collection('RAM').doc(RAM.ram_id.toString()); // Use OS.os_id as the document ID
      batch.set(docRef, RAM);
    });
  
    await batch.commit();
    console.log('RAM memory sticks added successfully!');
  }
  
  // Execute the function to add data
  addRAMs().catch(console.error);

